(#231) Revert to earlier version of Cak.Git
There is an error being thrown when using latest:

> Error: One or more errors occurred. (No error message has been provided by the native library)
No error message has been provided by the native library

Suspicion is that the upgrade to LibGitSharp latest version is causing problems:

https://github.com/cake-contrib/Cake_Git/releases/tag/v1.1.0